name: g_customer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  http: ^0.13.5
  moyasar: ^2.0.2
  pay: ^1.1.2
  firebase_messaging_web: ^3.5.11
  webview_flutter: ^4.4.2
  intl: ^0.18.0
  image: ^3.2.0
  lottie: ^2.3.0
  get_it: ^7.2.0
  flash: ^2.0.5+1
  shimmer: ^2.0.0
  location: ^4.4.0
  geocoding: ^2.1.0
  dotted_line: ^3.2.2
  auto_route: ^5.0.4
  flutter_svg: ^2.0.4
  google_place: ^0.4.7
  image_picker: ^0.8.7
  sms_autofill: ^2.2.0
  google_fonts: ^4.0.3
  url_launcher: ^6.1.9
  flutter_remix: ^0.0.3
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  path_provider: ^2.0.12
  google_sign_in: ^5.4.4
  razorpay_flutter: ^1.3.5
  cloud_firestore: ^4.4.5
  carousel_slider: ^4.2.1
  flutter_riverpod: ^2.3.2
  top_snackbar_flutter: ^2.1.1
  flutter_braintree: ^3.0.0
  connectivity_plus: ^3.0.3
  sign_in_with_apple: ^4.3.0
  pull_to_refresh: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  freezed_annotation: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.0.17
  firebase_messaging: ^14.3.0
  osm_nominatim: ^2.0.1
  google_maps_flutter: ^2.2.8
  flutter_html: ^3.0.0-alpha.6
  cached_network_image: ^3.2.3
  flutter_login_facebook: ^1.7.0
  intl_phone_field: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: 'assets/images/png/app_logo.png'

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/png/
    - assets/images/svg/
    - assets/
    - assets/images/
    - assets/images/temp_images/
